### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by samuelchassot** [calimero-project/calimero-tools#10]
Hi,

I tried to clone that repo to make some tests but the project is not building on my machine. I finally found the source of the problem:
in the file `ProcComm.java:613`, you call `LteHeeTag.from(tag);`. However this method was added to the calimero-core project around 10 days ago and the last release has 27 days. So, in the version of Calimero-core that is used here, this method does not exist.
There is another compilation error at `ProcComm.java:621` when `CEMILDataEx.newLte(...)` is called for the same reason (the method was added at the same time).

I hope this can help!

Best

**Comment by calimero-project** [comment]
Those are two methods that got refactored after the v2.5-rc1 tag. You can either compile at the rc1 tag, which will work fine, or if you fetch the latest sources, you will also need the head of calimero-core. If you build with Gradle and you put calimero-core into a sibling dir, tools will detect the changes automatically.

**Comment by samuelchassot** [comment]
I tried to build at rc1 tag (that is the `build.gradle` present already in this repo) but it does not work. If you navigate the code of the `calimero-core` at this tag (https://github.com/calimero-project/calimero-core/blob/v2.5-rc1/src/tuwien/auto/calimero/LteHeeTag.java) you can see that the method with signature `LteHeeTag.from(String);` is not there, as it was added in a more recent commit.

I'll try to build from the source instead
