### ISSUE TITLE
GroupAddresses are empty for mask version 0705 - BIM M112  during read of DeviceInfo

### ISSUE THREAD

**Issue by aparnasb24** [calimero-project/calimero-tools#11]
Hi all,

During peforming a read of DeviceInfo for KNX devices of mask version 0705 - BIM M112, the group addresses are empty using the calimero-tools.

My question is: How to obtain group addresses for different mask versions of KNX devices, since the group addresses for 0705 are empty.
How can I obtain the group addresses, for all different kinds of DD0's present in the DeviceDescriptor class.

Thank you for your help!

**Comment by bmalinowsky** [comment]
Did you get any error msg in the log, or did the tool complete normally? Device info should be able to read out the group addresses from devices with that device descriptor.

**Comment by aparnasb24** [comment]
There was one error message with the PEI type as follows:

**ERROR calimero.tools - reading actual PEI type (A/D converter channel 4, repeat 1)**

But further the tool completed with the Group address table entries and group addresses to be empty as below.

**Group Address Table Entries = 0
Group Addresses =**

**Comment by bmalinowsky** [comment]
That the address array will be empty when entries = 0 is expected. Do you know (e.g., from the ETS project) how many addresses there should be in the device?

I tried two 0705 devices, and they show the correct addresses.


If you like, you can manually recheck what's in the device memory. I explain it using the calimero-gui because it's probably easier:
1. Enter the device address in the top right field
2. Click Property Editor, and wait for it to fill the table
3. On the left, select Addresstable Object, and look in the main table for PID 7 `Table Reference`. (My guess is it has value 0x4000.)
4. Click Memory Editor, then, in the Offset field: enter the table reference value, and 10 for the number of Bytes. 
5. Click Read.
6. The first memory value at that location will be the number of group addresses.

This is basically the same procedure the device info tool does for finding the group addresses.

**Comment by aparnasb24** [comment]
Yes from the ETS project I know the number of group addresses present for a given device.

But with DeviceInfo tools the group addresses are empty, while ETS project has group addresses assigned to that device.

**Comment by aparnasb24** [comment]
I did try the calimero-gui for recheck of device memory, but the Property Editor function does not fill the table and the process is completed without any entries in the table.

**Comment by bmalinowsky** [comment]
What does the log window on the bottom and the log tab say?

**Comment by aparnasb24** [comment]
**Log window below says this:**

15:13:07:796 INFO calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - connection established (data endpoint 192.168.20.189:3671, channel 130, tunneling address 1.1.255)
15:13:07:829 INFO calimero.knxnetip.KNXnet/IP DevMgmt 192.168.20.189:3671 - connection established (data endpoint 192.168.20.189:3671, channel 131)
15:13:07:840 WARN calimero.link.192.168.20.189:3671 - wrong communication medium setting: using TP1 to access unknown medium
15:14:20:740 WARN calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - close connection - no heartbeat response





**And the log tab as below:**

15:16:12:763 DEBUG calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - establish connection from 192.168.20.24:54688 to 192.168.20.189:3671 (udp)
15:16:12:763 DEBUG calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - wait for connect response from 192.168.20.189:3671 ...
15:16:12:792 INFO calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - connection established (data endpoint 192.168.20.189:3671, channel 137, tunneling address 1.1.255)
15:16:12:792 DEBUG calimero.knxnetip.KNXnet/IP DevMgmt 192.168.20.189:3671 - establish connection from 192.168.20.24:45247 to 192.168.20.189:3671 (udp)
15:16:12:792 DEBUG calimero.knxnetip.KNXnet/IP DevMgmt 192.168.20.189:3671 - wait for connect response from 192.168.20.189:3671 ...
15:16:12:824 INFO calimero.knxnetip.KNXnet/IP DevMgmt 192.168.20.189:3671 - connection established (data endpoint 192.168.20.189:3671, channel 138)
15:16:12:824 TRACE calimero.knxnetip.KNXnet/IP DevMgmt 192.168.20.189:3671 - sending cEMI frame seq 0, WaitForCon, attempt 1 (channel 138) 06 10 03 10 00 11 04 8a 00 00 fc 00 08 01 33 10 01
15:16:12:835 TRACE calimero.knxnetip.KNXnet/IP DevMgmt 192.168.20.189:3671 - received service ack 0 from 192.168.20.189:3671 (channel 138)
15:16:12:836 WARN calimero.link.192.168.20.189:3671 - wrong communication medium setting: using TP1 to access unknown medium
15:16:12:837 TRACE calimero.knxnetip.KNXnet/IP DevMgmt 192.168.20.189:3671 - sending cEMI frame seq 1, WaitForCon, attempt 1 (channel 138) 06 10 03 10 00 11 04 8a 01 00 fc 00 00 01 38 10 01
15:16:12:902 TRACE calimero.knxnetip.KNXnet/IP DevMgmt 192.168.20.189:3671 - received service ack 1 from 192.168.20.189:3671 (channel 138)
15:16:12:902 DEBUG calimero.link.192.168.20.189:3671 - using max. APDU length of 55
15:16:12:903 TRACE calimero.knxnetip.KNXnet/IP DevMgmt 192.168.20.189:3671 - sending disconnect request for KNXnet/IP DevMgmt 192.168.20.189:3671 channel 138 (state OK)
15:16:12:969 DEBUG calimero.knxnetip.KNXnet/IP DevMgmt 192.168.20.189:3671 - close connection - user request
15:16:12:969 DEBUG calimero.link.192.168.20.189:3671 - hop count set to 6
15:16:12:970 DEBUG calimero.link.192.168.20.189:3671 - unsupported event type void tuwien.auto.calimero.tools.Main$1.connectionStatus(tuwien.auto.calimero.serial.ConnectionStatus)
15:16:12:970 TRACE calimero.mgmt.TL 192.168.20.189:3671 - created destination 1.1.1 (TL 192.168.20.189:3671) connectionless, no verify mode
15:16:12:971 TRACE calimero.xml - using StaX XMLStreamReader com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl
Object Index (OI), Property Index (PI), Object Type (OT), Property ID (PID)

**Comment by bmalinowsky** [comment]
Ok, that's strange. There is not a single send output, nor does the heartbeat warning show up in the log tab.

**Comment by aparnasb24** [comment]
If you could please suggest, how can I go about to fix this issue.


Thank you for your help!

**Comment by bmalinowsky** [comment]
Well, device info did mostly work from the command-line. So can you retry device info in the GUI (clear the log tab before), and attach the log output here? You don't need to copy the whole part, but starting from a line that 
goes something something like "DEBUG calimero.tools - read 1|23". (The number 1 might differ.) That line is in the last quarter of the log.

From the log I can see what the memory read does, and what is written at that location. Or if there is some other error.

**Comment by aparnasb24** [comment]
I am working with a virtual simulation of a KNX installation and not with real KNX devices. I have programmed the devices in the simulation using the ETS software and now using Calimero I am trying to access the virtual KNX installation.

**Log tab for memory read for 0x4000 is as below**

> read device memory range 0x4000 to 0x4001
> 03
> read device memory range 0x4001 to 0x4002
> 11
> read device memory range 0x4002 to 0x4003
> 01
> read device memory range 0x4003 to 0x4004
> 00
> read device memory range 0x4004 to 0x4005
> 01
> read device memory range 0x4005 to 0x4006
> 00
> read device memory range 0x4006 to 0x4007
> 65
> read device memory range 0x4007 to 0x4008
> 02
> read device memory range 0x4008 to 0x4009
> 01
> read device memory range 0x4009 to 0x400a
> 0a

**Comment by bmalinowsky** [comment]
So what does the device info log say when it tries to access either PID.TABLE or PID.TABLE_REFERENCE? If the reference property is used, it should contain 0x4000.

**Comment by aparnasb24** [comment]
When I perform a device memory read at 0x4000 I obtained the above data. But when I perform a property editor operation, the property table is empty.



**When I perform the device info operation, I get the logs as below:**

17:45:40:427 TRACE calimero.link.192.168.20.189:3671 - send 0.0.0->1.1.1 succeeded
17:45:40:428 DEBUG calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - received request seq 20 (channel 1) cEMI L-Data.con 1.1.255->1.1.1
17:45:40:430 DEBUG calimero.link.192.168.20.189:3671 - confirmation of 1.1.1
17:45:40:434 DEBUG calimero.tools - read 0x116..0x117 Group Address Table Entries
17:45:40:435 TRACE calimero.mgmt.TL 192.168.20.189:3671 - sending data connected to 1.1.1, attempt 1
17:45:40:435 DEBUG calimero.link.192.168.20.189:3671 - send (wait for confirmation) 0.0.0->1.1.1 L_Data.req, low priority hop count 6 repeat, tpdu 56 01 01 16
17:45:40:435 TRACE calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - sending cEMI frame seq 11, WaitForCon, attempt 1 (channel 1) 06 10 04 20 00 17 04 01 0b 00 11 00 bc 60 00 00 11 01 03 56 01 01 16
17:45:40:494 TRACE calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - received service ack 11 from 192.168.20.189:3671 (channel 1)
17:45:40:494 DEBUG calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - received request seq 21 (channel 1) cEMI L-Data.con 1.1.255->1.1.1
17:45:40:494 DEBUG calimero.link.192.168.20.189:3671 - confirmation of 1.1.1
17:45:40:495 TRACE calimero.link.192.168.20.189:3671 - send 0.0.0->1.1.1 succeeded
17:45:40:830 TRACE calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - received request seq 22 (channel 1) cEMI 29 00 bc 60 11 01 11 ff 00 d6
17:45:40:830 DEBUG calimero.link.192.168.20.189:3671 - indication 1.1.1->1.1.255 L_Data.ind, low priority hop count 6, tpdu d6
17:45:40:830 TRACE calimero.mgmt.TL 192.168.20.189:3671 - positive ack by 1.1.1
17:45:41:030 TRACE calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - received request seq 23 (channel 1) cEMI 29 00 bc 60 11 01 11 ff 04 56 41 01 16 00
17:45:41:030 DEBUG calimero.link.192.168.20.189:3671 - indication 1.1.1->1.1.255 L_Data.ind, low priority hop count 6, tpdu 56 41 01 16 00
17:45:41:030 DEBUG calimero.link.192.168.20.189:3671 - send 0.0.0->1.1.1 L_Data.req, system priority hop count 6 repeat, tpdu d6
17:45:41:031 TRACE calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - sending cEMI frame seq 12, WaitForAck, attempt 1 (channel 1) 06 10 04 20 00 14 04 01 0c 00 11 00 b0 60 00 00 11 01 00 d6
17:45:41:095 TRACE calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - received service ack 12 from 192.168.20.189:3671 (channel 1)
17:45:41:095 TRACE calimero.link.192.168.20.189:3671 - send 0.0.0->1.1.1 succeeded
17:45:41:096 DEBUG calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - received request seq 24 (channel 1) cEMI L-Data.con 1.1.255->1.1.1
17:45:41:097 DEBUG calimero.link.192.168.20.189:3671 - confirmation of 1.1.1
17:45:41:098 TRACE calimero.mgmt.TL 192.168.20.189:3671 - send disconnect to 1.1.1
17:45:41:098 DEBUG calimero.link.192.168.20.189:3671 - send (wait for confirmation) 0.0.0->1.1.1 L_Data.req, system priority hop count 6 repeat, tpdu 81
17:45:41:099 TRACE calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - sending cEMI frame seq 13, WaitForCon, attempt 1 (channel 1) 06 10 04 20 00 14 04 01 0d 00 11 00 b0 60 00 00 11 01 00 81
17:45:41:161 TRACE calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - received service ack 13 from 192.168.20.189:3671 (channel 1)
17:45:41:162 DEBUG calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - received request seq 25 (channel 1) cEMI L-Data.con 1.1.255->1.1.1
17:45:41:162 DEBUG calimero.link.192.168.20.189:3671 - confirmation of 1.1.1
17:45:41:163 TRACE calimero.link.192.168.20.189:3671 - send 0.0.0->1.1.1 succeeded
17:45:41:164 TRACE calimero.mgmt.TL 192.168.20.189:3671 - disconnected from 1.1.1
17:45:41:175 DEBUG calimero.mgmt.TL 192.168.20.189:3671 - detached from tunneling link 192.168.20.189:3671 TP1 medium, device 0.0.0, hopcount 6
17:45:41:175 DEBUG calimero.mgmt.MC 192.168.20.189:3671 - detached from tunneling link 192.168.20.189:3671 TP1 medium, device 0.0.0, hopcount 6
17:45:41:175 TRACE calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - sending disconnect request for KNXnet/IP Tunneling 192.168.20.189:3671 channel 1 (state OK)
17:45:41:228 DEBUG calimero.knxnetip.KNXnet/IP Tunneling 192.168.20.189:3671 - close connection - user request
17:45:41:228 DEBUG calimero.link.192.168.20.189:3671 - link closed

**Comment by bmalinowsky** [comment]
Now we're getting somewhere. There is the log entry 

read 0x116..0x117 Group Address Table Entries

which means that the table is read from that memory location. This is done if the device does not have an address table interface object. A mask 0705 device should have one.

**Comment by aparnasb24** [comment]
And also if through calimero-tools if I perform the below operation on Property.java

--localhost 192.168.20.24 192.168.20.189 -p 3671 --medium TP1 -r 1.1.1 scan all

I get the below output:

Object Index (OI), Property Index (PI), Object Type (OT), Property ID (PID)



With no properties entries in them.

But in the DeviceInfo.java from the calimero-tools if I do the following modifications in the readGroupAddresses( ) function

	if (dd.equals(DD0.TYPE_5705))  //  **replacing 5705 with 0705**
			memLocation = addrGroupAddrTableMask5705;

Then I obtain the group addresses for 0705 as below:

Device Descriptor = 0705 - BIM M112
Knx Medium = Twisted Pair 1
Firmware Type = BIM M112
Firmware Version = 0
Programming Mode = off
Group Address Table Entries = 3
Device Address = 1.1.1
Group Addresses = 0/0/1, 0/0/101

**Comment by aparnasb24** [comment]
If you could please suggest how could I go about fixing the **address table interface object** issue. So that it works for all different mask versions of KNX devices.



Thank you for help!
