### ISSUE TITLE
Can ScanDevices, DeviceInfo and using ProcComm tool for read and group monitor functionalities peformed simultaneoulsy?

### ISSUE THREAD

**Issue by aparnasb24** [calimero-project/calimero-tools#12]
Hi all,

I want to be using Calimero library, to obtain details of KNX devices and their values based on their obtained group addresses.

I want to perform operations to Discover the IP interface, ScanDevices, DeviceInfo and read the values based on the group address.

But we aim to keep the group monitor in execution, while simultaneously be able to perform ScanDevices, DeviceInfo, perform read for a group address using the ProcComm tool and also record any real time changes taking place in the KNX installation.

Is this something that Calimero library offered, or can you please suggest any fix where this can be achieved.

Since currently we are unable to obtain the changes taking place over the KNX bus during the group monitor operation, while we perform any other operation alongside like ScanDevices, DeviceInfo or a read using ProComm tool.

Thank you for your help!

**Comment by calimero-project** [comment]
You can run the tools in parallel.
If you want to observe all traffic, you have to use either traffic monitor or network monitor. Group monitor is for process communication only (group addresses).

**Comment by aparnasb24** [comment]
Thank you for the information. But currently when I try to run the tools in parallel, the group monitor stops recording any changes that took place with the group addresses of the devices, which otherwise would record all the changes that happened to the group address values.

Is there something that I am missing while running these tools in parallel, since I am not able to get all the changes that took place with the group address of the devices.

Thank you for help!

**Comment by calimero-project** [comment]
All tools function completely independent from each other. If the output stops if you run other stuff, it's more likely a problem of the server.

**Comment by aparnasb24** [comment]
If you could please suggest how could I go about fixing this issue, since I would want to run these tools in parallel and obtain the information.


Thank you for your help!

**Comment by bmalinowsky** [comment]
Is this still an issue?

**Comment by aparnasb24** [comment]
Yes it is still an issue

**Comment by bmalinowsky** [comment]
Then please add more information. It was stated above that the tools run independently. What if you start the tools in parallel but on different computers or in different containers. Does it also happen?

**Comment by aparnasb24** [comment]
Hi

If I run two separate instances of the Calimero tools project, in which one instance has the ProcComm for a read or write operation and the other instance has the monitor of the ProcComm tool. When there is change in the state of the light bulb through the push button the changes reflect in the group monitor. Whereas if there is read or write operation performed through the ProcComm tool of the Calimero library.., the changes taken place in the state of the light bulb are not reflected in the group monitor..


If you could please suggest how could we go about fixing this issue.., since I would want to run these tools in parallel to obtain the changes taken place..


Thank you for your help!

**Comment by aparnasb24** [comment]
Even if the tools are started in parallel on different computers also, the changes taken place are not recorded in the group monitor running on another computer.

**Comment by bmalinowsky** [comment]
A read does not change the state, but you should receive a read response with the current state. If not, then it can be that no one sent a response. You have to check your ETS project.

The effect from a from a write is only visible if the light bulb is configured to send a change notification. You can configure that in the ETS project where you added the light bulb.

**Comment by aparnasb24** [comment]
The changes do get recorded in the group monitor when there is a change from the KNX installation side, like the switching on/off of a light bulb through the push button. But when there is a write operation performed through the ProcComm tool to the group address associated with the switching of the light bulb, the group monitor does not record any changes that took place.

**Comment by bmalinowsky** [comment]
I think what you see is the write from the push button, check the source address.

**Comment by aparnasb24** [comment]
Yes the write is from the push button. And the logs for group monitor look something like this.

20:41:37.779 1.1.2->0/0/1  A_Group.write 00: off
20:41:37.794 1.1.1->0/0/101  A_Group.response 00: consumer [1.1200], 0 false [2.002], decrease break [3.007]
20:42:28.495 1.1.2->0/0/1  A_Group.write 01: on
20:42:28.520 1.1.1->0/0/101  A_Group.response 01: producer [1.1200], 0 true [2.002], decrease 1 steps [3.007]

Where 1.1.1 is the switch actuator and 1.1.2 is the push button
