### ISSUE TITLE
Docker image for Raspbian

### ISSUE THREAD

**Issue by MMartinezV** [calimero-project/calimero-tools#16]
Hi,

Could you publish on Docker Hub the docker image for platform ARM? Months ago you published the knxserver's one and it works great. I'd like to have the knxtools also to do some tests.

Regards,

  Manuel Martínez

**Comment by bmalinowsky** [comment]
Tools for ARMv7 are now on docker hub. Give it a try.

**Comment by MMartinezV** [comment]
It works fine.
Thank you
