### ISSUE TITLE
Discover tool and KNXnet/IP Description request misleading documentation and usage

### ISSUE THREAD

**Issue by fritzpraus** [calimero-project/calimero-tools#18]
Dear Boris,
when running the Discover tool with the intent to just issue a KNXnet/IP description request (without search) the documentation and usage propose the following prompt: 
`./gradlew run --args "discover --udp describe 192.168.0.11"`

This, however, misleads to a KNXnet/IP Search Request extended
```
Frame 122: 56 bytes on wire (448 bits), 56 bytes captured (448 bits) on interface XXX, id 0
Ethernet II, Src: XXX, Dst: XXX
Internet Protocol Version 4, Src: 192.168.0.138, Dst: 192.168.0.11
User Datagram Protocol, Src Port: 47390, Dst Port: 3671
KNX/IP Search Request Extended, Discovery @ 192.168.0.138:47390
    KNX/IP Header: Search Request Extended
    HPAI Discovery Endpoint: 192.168.0.138:47390 UDP
```
The cause lies in Main.java line 101/102
```
{ "discover", "Discover KNXnet/IP devices", "search" },
{ "describe", "KNXnet/IP device self-description", "describe" },
```
Calling `discover` adds the default arg `search` and thus Discover.java line 238 issues a search request and not a description request.
Example output with added `System.out` of `args`:
```
./gradlew run --args "discover --udp describe 192.168.0.11"
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :run
search
--udp
describe
192.168.0.11
Juni 06, 2023 6:43:41 AM io.calimero.tools.Discover onCompletion
SCHWERWIEGEND: completed
io.calimero.KNXTimeoutException: timeout waiting for response from /192.168.0.11:3671
        at io.calimero.tools@3.0-SNAPSHOT/io.calimero.tools.Discover.joinOnResult(Discover.java:464)
        at io.calimero.tools@3.0-SNAPSHOT/io.calimero.tools.Discover.search(Discover.java:382)
        at io.calimero.tools@3.0-SNAPSHOT/io.calimero.tools.Discover.run(Discover.java:238)
        at io.calimero.tools@3.0-SNAPSHOT/io.calimero.tools.Discover.main(Discover.java:216)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:577)
        at io.calimero.tools@3.0-SNAPSHOT/io.calimero.tools.Main.main(Main.java:202)
```

Fix is obvious,  but undocumented. The correct command to issue a KNXnet/IP Description Request is:
`./gradlew run --args="describe 192.168.0.11"`

Best regards
Fritz

**Comment by bmalinowsky** [comment]
Hello Fritz!

I might miss something, but is the issue that the commands for search/discovery and self-description differ? If you just run `./gradlew run`, you get the usage output

```
discover - Discover KNXnet/IP devices // <--- discovers KNX IP devices (does a search), use the --withDescription option for description of each discovered device
describe - KNXnet/IP device self-description // <--- request self-description of a single KNX IP device
...
```

but when you run `./gradlew run --args "describe -h" `, you still get the `search` command?


`discover` & `search` are equivalent commands (but they depend on the invocation, unfortunately). 

P.S. `search` was not kept because I thought of searching for other devices as well (RF, USB, TP-UART via USB). So a simple `search` would give you all KNX devices (also non-IP like in the GUI). Never implemented.

-- Boris
