### ISSUE TITLE
read value from knx devies faild

### ISSUE THREAD

**Issue by MichaelGottschlich** [calimero-project/calimero-tools#2]
Hallo,
read command failed. Is a bug or wrong command to read a value from knx device?

IP localhost: 10.17.20.177
KNX router: 10.17.10.2
KNX Device: group address is 2/1/1 is a light switch and the light is on

Java version:
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

mvn exec:java -Dexec.mainClass=tuwien.auto.calimero.tools.ProcComm -Dexec.args="-localhost 10.17.20.177 10.17.10.2 read bool 2/1/1"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Calimero Tools 2.3
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ calimero-tools ---
completed, no confirmation reply received for L-Data.req from 0.0.0 to 2/1/1, low priority hop count 6 repeat tpdu 00 00
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.730 s
[INFO] Finished at: 2017-07-05T09:17:14+02:00
[INFO] Final Memory: 9M/150M
[INFO] ------------------------------------------------------------------------

Monitor from ETS5:
![image](https://user-images.githubusercontent.com/9129376/27854752-3a73a234-6168-11e7-9b8d-e8158fcbb725.png)

**Comment by calimero-project** [comment]
Hi,
the command is correct. The error "no confirmation ..." means that the confirmation of the sent read request is missing.
Can you try the command with verbose output (`-verbose`), and then also with `-nat`, to see more details or any changes in behavior?

**Comment by MichaelGottschlich** [comment]
hallo,

the comand with -verbose and -nat option.

mvn exec:java -Dexec.mainClass=tuwien.auto.calimero.tools.ProcComm -Dexec.args="-verbose -nat -localhost 10.17.20.177 10.17.10.2 read bool 2/1/1"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Calimero Tools 2.3
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ calimero-tools ---
establish connection from /10.17.20.177:49667 to /10.17.10.2:3671
wait for connect response from /10.17.10.2:3671 ...
NAT aware mode: using server data endpoint /10.17.10.2:3671
connection established
send message to 2/1/1, wait for confirmation
cEMI L-Data.req from 0.0.0 to 2/1/1, low priority hop count 6 repeat tpdu 00 00
sending cEMI frame seq 0, wait for cEMI.con, attempt 1 (channel 2) 06 10 04 20 00 15 04 02 00 00 11 00 bc e0 00 00 11 01 01 00 00
received cEMI L-Data.con with req 0
confirmation of 2/1/1
indication from 1.2.1
response timeout waiting for confirmation, no confirmation reply received for L-Data.req from 0.0.0 to 2/1/1, low priority hop count 6 repeat tpdu 00 00
detached from 10.17.10.2:3671
close connection - user request
link closed
completed, no confirmation reply received for L-Data.req from 0.0.0 to 2/1/1, low priority hop count 6 repeat tpdu 00 00
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.750 s
[INFO] Finished at: 2017-07-05T15:52:40+02:00
[INFO] Final Memory: 9M/150M
[INFO] ------------------------------------------------------------------------

**Comment by calimero-project** [comment]
I compared the log to the expected output, and the link layer send does not complete. I guess the received confirmation frame does not pass the checks to move on. Do you by any chance use a Gira router? There was a problem with cEMI additional info which got added to the frames.

If yes, you can give the same example a try using a 2.4 snapshot version, where that unknown info blocks are removed.

**Comment by MichaelGottschlich** [comment]
hi, 

is works, with 2.4 snapshot. Is 2.4 version released? 

I use an gira router.

 mvn exec:java -Dexec.mainClass=tuwien.auto.calimero.tools.ProcComm -Dexec.args="--verbose --nat --localhost 10.17.20.177 10.17.10.2 read bool 2/1/1"
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Calimero Tools 2.4-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- exec-maven-plugin:1.4.0:java (default-cli) @ calimero-tools ---
11:11:31:016 INFO calimero.knxnetip.KNXnet/IP Tunneling 10.17.10.2:3671 - establish connection from /10.17.20.177:53497 to /10.17.10.2:3671
11:11:31:027 INFO calimero.knxnetip.KNXnet/IP Tunneling 10.17.10.2:3671 - connection established (channel 2)
11:11:31:062 WARN calimero.knxnetip.KNXnet/IP Tunneling 10.17.10.2:3671 - remove L-Data additional info type 6: 60a96227
11:11:31:062 WARN calimero.knxnetip.KNXnet/IP Tunneling 10.17.10.2:3671 - remove L-Data additional info type 128: 4515
read 2/1/1 value: true
11:11:31:140 INFO calimero.process.process 10.17.10.2:3671 - detached from 10.17.10.2:3671
11:11:31:146 INFO calimero.knxnetip.KNXnet/IP Tunneling 10.17.10.2:3671 - close connection - user request
11:11:31:147 INFO calimero.link.10.17.10.2:3671 - link closed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.940 s
[INFO] Finished at: 2017-07-10T11:11:31+02:00
[INFO] Final Memory: 12M/150M
[INFO] ------------------------------------------------------------------------

**Comment by calimero-project** [comment]
No, v2.4 is not released, nor is there any release date.

**Comment by MichaelGottschlich** [comment]
Thank you for your help.
