### ISSUE TITLE
GroupAddresses empty when read device infos

### ISSUE THREAD

**Issue by LamelDev** [calimero-project/calimero-tools#5]
Hi everyone, 

I don't know if I've missed something but it appear the group addresses are exmpty when I try to read device informations using _calimero-tools_, same behaviour is seen when using _calimero-gui_.

If I look to the code of DeviceInfo class, it appear that group addresses are read at address **0x0116** in the device memory:

`private static final int addrGroupAddrTable = 0x0116;`

My question is: It is normal that the memory read return me always empty data? And where in the doc I can find the memory organisation for a device(I've searched in so many technical documentation, maybe I missed it)? 

Thank you for you help!

**Comment by bmalinowsky** [comment]
The gui is a graphical wrapper around the tools, so it's quite likely you'll see the same results there.

The table memory address you cite is used by many knx devices, but some do have a different lookup. I committed a change (6d98ec503efdd1d8544db4304886232a9b565a6d) that is more observant to different implementations. Please try if that works better in your case.

I know of 9 different group address table realizations, which are mostly the same, but in some details are not; you need to read the knx spec for all the gory details.

For the device info tool, I did not make the effort to tabularize all the different DD0s to "know" which variant is the appropriate one (which, btw., is also the reason why some of the services time out, and the whole procedure takes some time).

**Comment by LamelDev** [comment]
Hi @bmalinowsky,

Thanks for your update it works like a charm in my case now!

I'll take a look at KNX specs to better understand what happened here.
