### ISSUE TITLE
Command line help incorrect

### ISSUE THREAD

**Issue by Race666** [calimero-project/calimero-tools#6]
Hi,

[Command line help](https://github.com/calimero-project/calimero-tools/blob/6d98ec503efdd1d8544db4304886232a9b565a6d/src/tuwien/auto/calimero/tools/ProcComm.java#L927) of write/read does not show the expected order:
```
java -jar /opt/calimero-server/calimero-tools-2.4-rc1.jar write
Available commands for process communication:
  read <DPT> <KNX address>           read from group address
  write <DPT> <value> <KNX address>  write to group address
```
Correct order is
```
write <KNX address> <DPT> <value>
```

Used  [ProcComm.java](https://github.com/calimero-project/calimero-tools/blob/6d98ec503efdd1d8544db4304886232a9b565a6d/src/tuwien/auto/calimero/tools/ProcComm.java#L192) as reference.

Michael

**Comment by bmalinowsky** [comment]
@Race666 Thank you for your report!

**Comment by Race666** [comment]
@bmalinowsky Thanks for your work! I recommended some vistor of my blog to switch from knxd to calimero (knxd has some issues USB interfaces) and [it works great](https://github.com/knxd/knxd/issues/415#issuecomment-550144640).
