### ISSUE TITLE
USB Interface exits with waiting for response error

### ISSUE THREAD

**Issue by Doomcurry** [calimero-project/calimero-tools#7]
Hello,

it might be that I looked over something but for me using the calimero-tools doesn't seem to work.
I am trying to use maven to speak to this [USB Interface](https://www.weinzierl.de/index.php/de/alles-knx1/knx-devices/knx-usb-interface-312).
But so far it always exited with this error:
![Error](https://user-images.githubusercontent.com/58102132/89394393-51ca1900-d70c-11ea-901b-b695248b9be7.PNG)
I don't have a clue why it does that, any help would be very appreciated.

**Comment by bmalinowsky** [comment]
Can you please rerun the same with loglevel _trace_ and post the output so i can see if there is any response at all sent by the device?

**Comment by Doomcurry** [comment]
Here is the picture of what I think is the important part, 
![Error2](https://user-images.githubusercontent.com/58102132/89495001-9a8adc00-d7b7-11ea-8e9a-603afe4079c2.PNG)
but just to be sure i also added a [log file](https://github.com/calimero-project/calimero-tools/files/5032789/log.txt).
I ran it with the same configuration as above (except the loglevel).

**Comment by bmalinowsky** [comment]
While in the picture there is not a single response, in the log file there is a response for the first request (isKnxConnectionActive at timestamp 07:11:21:025). But then there is no response for the second request. So this makes me think that some responses are delayed too much (arrive after the response timeout). The timeout for knx usb communication is 1 second.

**Comment by Doomcurry** [comment]
Is there anything I can do to troubleshoot this? I thought since I set it up with ETS, that this would work too. The interface is directly connected via an USB cable so I really don't know what can even be done against the timeout.

**Comment by bmalinowsky** [comment]
Since you also have a windows machine, does it work there, i.e., usb interface + tools? Or does it lead to the same error. On linux, if you are familiar with usbmon or wireshark you can check the timing there.

The issue is not with the timeout (1 s is a long time, and internally I actually wait 1.5 s), but to figure out why there is sometimes no (or otherwise a quite delayed) response during setup.

**Comment by Doomcurry** [comment]
Well so far I did find one thing which seems quit interesting.
Here is the [link](https://michlstechblog.info/blog/raspberry-pi-eibd-with-a-knx-usb-interface/). I am aware that this is a post about eibd but maybe it is useful to you.
Here is the part I find interesting:
> Update 2 13.02.2015:A user reports that the USB devices (ID 0e77:0104) from Weinzierl or Lingg&Lanke has the problem that telegrams can be send to but no pakets are received from the KNX bus. This is a known issue and already discussed at the bcusdk mailing list.
I'll soon follow this up with more logs (from Windows and Linux).

**Comment by calimero-project** [comment]
Please reopen if this is still relevant.
