### ISSUE TITLE
Feature Request/Documentation: execute pre-build JAR

### ISSUE THREAD

**Issue by danielWQ** [calimero-project/calimero-tools#9]
You provided excellent documentation on how to run the project using Gradle or Maven out of the source code or even with plain Java using the JAR (but one has to provide the dependencies manually).

It would be convenient to have an one-liner to download and start the program - without the need the have/compile the sourcecode.

Proposal:
**build.gradle**
```gradle
plugins {
    id 'application'
}
repositories { mavenCentral() }
mainClassName = "tuwien.auto.calimero.tools.Main"

dependencies {
  runtimeOnly group: 'com.github.calimero', name: 'calimero-tools', version: '2.4'
}
```

Run with:
```
./gradlew run --args="monitor 192.168.115.6"
```

**Comment by bmalinowsky** [comment]
Thanks! I put it in the readme. The gradle wrapper still has to be done manually, if desired.
